#!/bin/bash
# pre-commit git hook to check the validity Ruby files
# 
# Prerequisites:
#   gem install ruby-lint
# 
# Install: 
#  /path/to/repo/.git/hooks/pre-comit
 
echo "### ruby-lint ###"
for file in `git diff --name-only --cached | grep -E '\.(rb)'`
do
    # Only check new/modified files
    if [[ -f $file ]]
    then
        ruby-lint $file
        # Set us up to bail if we receive any syntax errors
        if [[ $? -ne 0 ]]
        then
            syntax_is_bad=1
        fi
    fi
done

echo "### ruby -c FILE ###"
for file in `git diff --name-only --cached | grep -E '\.(rb)'`
do
    # Only check new/modified files
    if [[ -f $file ]]
    then
        ruby -c $file
        # Set us up to bail if we receive any syntax errors
        if [[ $? -ne 0 ]]
        then
            syntax_is_bad=1
        fi
    fi
done

if [[ $syntax_is_bad -eq 1 ]]
then
    echo "FATAL: Syntax is bad. See above errors"
    exit 1
fi
